### ISSUE TITLE
A485 patches

### ISSUE THREAD

**Issue by mid-kid** [digmorepaka/thinkpad-firmware-patches#11]
I've successfully been able to apply [the patches to upen up the AMD menu](https://github.com/digmorepaka/thinkpad-firmware-patches/blob/master/xx85_xx95_patches_v1.txt#L27), and it works fine.

I've loaded the related PE files into a disassembler, but I can't figure out what the data that's being edited by these patches represents. I'm wondering if there might be more hidden menus that can be enabled? Is there any documentation on what this data means?

Specifically, I'm wondering if there might be some option to control the amount of VRAM? I'd like to expand it a bit beyond the defaults...

**Comment by digmorepaka** [comment]
They reveal the AMD CBS and PBS menus, anything that's in there and functional is accessible.

**Comment by mid-kid** [comment]
I see, I was hoping there'd be more hidden menus beyond the AMD menu. Shame.
