### ISSUE TITLE
Any hope for a patch for x90 series thinkpad?

### ISSUE THREAD

**Issue by antoniomcr96** [digmorepaka/thinkpad-firmware-patches#17]
I was wondering why there isn't any patch for x90 thinkpads (T490, L390, X390 and so on). They share the same board, so if you patch one of them you'll have a patch for every laptop.

I can provide a dump of L390 yoga bios if somehow useful.

**Comment by digmorepaka** [comment]
No, tamper protection bypass is needed first. Feel free to make a pull request if you figure it out.
