### ISSUE TITLE
T440p XMP profile selector not working properly

### ISSUE THREAD

**Issue by renoxtv** [digmorepaka/thinkpad-firmware-patches#19]
After applying xx40_xx50_patches_v7.txt with the "show XMP and manual memory timings (cleaned up)"  enabled, I now have options to select a memory profile. With a normal non XMP stick, I get Default Profile, XMP 1 and XMP 2, with XMP 1 profile having manual timing control, but CAS latency can go only to 10 and not any higher which is not acceptable. After I flashed a XMP profile to my RAM's SPD, I now only have XMP Profile 1 as an option with the manual timings, which in this case, CL10 is too low and the laptop won't boot with it. Tried flashing 2 different XMP profiles, even to a ram stick that was not the OEM hynix one, no dice. Attached some pics
![photo_2022-05-07_20-11-12](https://user-images.githubusercontent.com/38763593/167264707-c435bf90-db89-428d-9bf2-d72554e97511.jpg)
![photo_2022-05-07_20-11-39](https://user-images.githubusercontent.com/38763593/167264717-03436b26-3d32-486b-a53d-6034cbee2081.jpg)

**Comment by digmorepaka** [comment]
Not sure how you flashed XMP in a T440p, haswell MRC has SPD+XMP write disabled. Regardless, nothing  I can do about this.
