### ISSUE TITLE
T470S Firmware patch

### ISSUE THREAD

**Issue by hamcuks** [digmorepaka/thinkpad-firmware-patches#21]
Hi, can you make patch for t470s? I've apply the patch (xx70_xx80_patches_v7) to my t470s BIOS, but no luck

My laptop beeping 5 times, but not boot to BIOS or OS. Just black screen

Thanks in advance!

**Comment by digmorepaka** [comment]
> replace 4C 4E 56 42 42 53 45 43 FB with 4C 4E 56 42 42 53 45 43 FF


Have you done  this  step?

**Comment by hamcuks** [comment]
> > replace 4C 4E 56 42 42 53 45 43 FB with 4C 4E 56 42 42 53 45 43 FF
> 
> Have you done this step?

Oh sorry, I forget to replace that. Let me try, I'll report later...

**Comment by hamcuks** [comment]
> 

Sorry, I don't understand how to replace the hex number. Using UEFIReplace or what?

Thank you

**Comment by digmorepaka** [comment]
.....a hex editor

**Comment by hamcuks** [comment]
Hi, I'm sorry for late reply. Now, I success unlock the advanced tab. I was forgot to replace replace 4C 4E 56 42 42 53 45 43 FB with 4C 4E 56 42 42 53 45 43 FF

![advanced tab](https://drive.google.com/file/d/1MD0a6nFQJAHPlKRV8WRv-cDMwvoRU7u-/preview)
