### ISSUE TITLE
X1 Carbon 6th owners, if your Thunderbolt and HDMI is working we need your ROM dump

### ISSUE THREAD

**Issue by jnada2021** [digmorepaka/thinkpad-firmware-patches#25]
X1 Carbon 6th owners, if your Thunderbolt and HDMI is working we need your ROM dump

Mods please delete if inappropriate and apologies in advance. I am very sorry for asking this here but situation is dire. 

I am desperately looking for some X1 Carbon 6th gen owners with CH341a SPI Programmer and SOIC8 Clip and whose X1 Carbon Thunderbolt and HDMI ports work properly to extract the bin file in their laptop and share with us since our HDMI nor DP from TB ports do not work at all due some intel ME firmware is messing up things.

https://www.reddit.com/r/thinkpad/comments/rsri27/urgent_wanted_x1c6_thunderbolt_working_bin_file/
https://github.com/fwupd/firmware-lenovo/issues/264

Thank you again and all the best

**Comment by digmorepaka** [comment]
Unrelated spam
