### ISSUE TITLE
W541 is not seeing m2 ssd after bios patch

### ISSUE THREAD

**Issue by gassity** [digmorepaka/thinkpad-firmware-patches#26]
Everything is working fine, except  for m.2 ssd, which worked good before patching.
No matter how I try. With every bios settings I've tried.
It's not being detected both in BIOS and Windows.

SSD is working fine itself. Checked in another laptop.

What could be the problem?

**Comment by digmorepaka** [comment]
Make sure the sata port that it is attached to is enabled of course start by loading defaults.

**Comment by gassity** [comment]
> Make sure the sata port that it is attached to is enabled of course start by loading defaults.

yep, sure. Already done, but no luck. Maybe there's some specific setting in "Advance menu"?

**Comment by digmorepaka** [comment]
> Maybe there's some specific setting in "Advance menu"
Yes, check if the sata port is enabled.

**Comment by gassity** [comment]
Sure) It sees my other 2.5 SSD and DVD-Rom. I've tried to even unplug them for any interference, but still no luck. Led on the m.2 ssd lights up and that's it.

**Comment by dnsound** [comment]
Same issue for me, did the bios patching to my W541 for the advanced menu and my m.2 ssd is no more detected.
I also tried booting with coreboot but the issue persist.
