### ISSUE TITLE
ThinkPad 13 Gen 1

### ISSUE THREAD

**Issue by BergamotGreenTea** [digmorepaka/thinkpad-firmware-patches#29]
<html><body>

Model | ThinkPad 13
-- | --
Patchset | Default for generation (SkyLake)
TPM | No
Notes | Advanced UEFI menu unlocked, wwan whitelist removal not tested. No wwan slot availlable on this model, I will test in the wan slot if I get my hands on a card. Relevant hex was found and replaced during patching.

</body>
</html>

**Comment by digmorepaka** [comment]
I will wait until you test WLAN  whitelist removal until marking it as supported, Thanks
