### ISSUE TITLE
ThinkPad 11e Gen 6 is Supported

### ISSUE THREAD

**Issue by loll70** [digmorepaka/thinkpad-firmware-patches#32]
<html>
<body>

Model | ThinkPad 11e Gen 6
-- | --
Patchset | xx70_xx80_patches_v7.txt
TPM | Yes, Hex was already fixed
Notes | None

</body>
</html>

**Comment by loll70** [comment]
tested config with i5-8200y

**Comment by digmorepaka** [comment]
Does the TPM work when you try to provision it?
