### ISSUE TITLE
do i need 1.8v adapter for the CH341A for T480?

### ISSUE THREAD

**Issue by VinylNerd** [digmorepaka/thinkpad-firmware-patches#46]
do i need the 1.8v adapter or will item linked below work? i didnt use the adapter for my T440P before but i returned that CH341A to amazon when i was done with it lol

https://www.ebay.ca/itm/165928313612?itmmeta=01HS9VXV02KGKMQBE50F6SDGVE&hash=item26a219230c:g:rtUAAOSwVWdhpMnC&itmprp=enc%3AAQAJAAAA4D%2BrwJzquBeAX4k66nXOoz5WlsUwZxeAu%2B65uDu7ZRJ10K8Ap7N7Rr92LrrlWiKY81wyVJFcOpNuDW8H2axpL%2FFr7B6DJBsJ2UZppX5bYuouJwXc2YgrqrDJAGAmTScISIj1e8Svns7fmZCOyUw30gBn44W3VmnTwnZc%2BRcRxPTtsr9T7sBYxCI9frArZQ%2FSFpNQGfa5Mj59ElYT1KltvW1EaYJYuXHFegrh4Da9tgxST5NGNocemf67hMr9YaWUfh%2Bj%2B%2FY81yyQxMsirzTIHVJcG0AysmsMx4TPzc6I4SO%2B%7Ctkp%3ABFBMkLD3u8pj

**Comment by digmorepaka** [comment]
T480 is 3.3V, same setup as for your T440p will work fine. The only difference is that it is a single SPI IC, not two in an opaque split rom.
