### ISSUE TITLE
ThinkPad T14 Gen 1 AMD patches dont work

### ISSUE THREAD

**Issue by wucke13** [digmorepaka/thinkpad-firmware-patches#48]
| Model | T14 Gen 1 AMD |
| --- | --- |
| Patchset | Default for generation |
| TPM | No |
| Notes | No post |

# Attempt 1

```
#LenovoMfgDoneDxe | protection bypass test 1
93E18521-9E52-4EEB-A230-7C24B2EC03E8 10 P:790F48B80E:E9AB020000    

#SystemFormBrowserMetroViewDxe | enable 'AMD' menu on metroUI | AMD PBS and CBS | Lenovo T14
C7351A96-9215-4026-BCBD-12D6E7DB36E9 10 P:64FEC13DB537F64B9BCF4F0689299E53:92C3454EE23234418FB006E7390F22F3    
```

followed by

> replace `4C 4E 56 42 42 53 45 43 FB` with `4C 4E 56 42 42 53 45 43 FF` on the previously patched binary

Result: boot loop, nothing on screen, probably fails to post.

# Attempt 2

```
#LenovoMfgDoneDxe | protection bypass test 1
93E18521-9E52-4EEB-A230-7C24B2EC03E8 10 P:790F48B80E:E9AB020000    

# SystemFormBrowserCoreDxe | enable 'AMD' menu | AMD PBS and CBS | Lenovo T14
# use classic view, not metroUI
721C8B66-426C-4E86-8E99-3457C46AB0B9 10 P:04320b483cc2e14abb16a73fadda475f:92C3454EE23234418FB006E7390F22F3         
32442D09-1D11-4E27-8AAB-90FE6ACB0489 10 P:04320b483cc2e14abb16a73fadda475f:92C3454EE23234418FB006E7390F22F3       
```

followed by

> replace `4C 4E 56 42 42 53 45 43 FB` with `4C 4E 56 42 42 53 45 43 FF` on the previously patched binary

Result: boot loop, nothing on screen, probably fails to post.

**Comment by digmorepaka** [comment]
As is written in the readme, these models aren't supported just yet. The patches are probably fine, but a tamper protection bypass is not yet public.
