### ISSUE TITLE
Firmware patch for the P50?

### ISSUE THREAD

**Issue by Wasmachineman-NL** [digmorepaka/thinkpad-firmware-patches#5]
Title. What patch do I need for my P50 to unlock the BIOS? xx60?

**Comment by digmorepaka** [comment]
Yes.

**Comment by Wasmachineman-NL** [comment]
Cool, thanks. A project for another day I suppose.

**Comment by Wasmachineman-NL** [comment]
Took three years but I finally took the plunge after modding my P51. I can confirm the xx60 and xx70 patches work for the P50 and P51 respectively.

**Comment by digmorepaka** [comment]
Thanks
