### ISSUE TITLE
TPM sign required on t480, unclear

### ISSUE THREAD

**Issue by dodoradio** [digmorepaka/thinkpad-firmware-patches#6]
please change 'To get a working TPM use Thrimbor's uefi-sign for xx20, xx30, and xx40 ThinkPads. For soldered xx40, xx50 and xx80 replace 4C 4E 56 42 42 53 45 43 FB with 4C 4E 56 42 42 53 45 43 FF on the previously patched binary' to say that you MUST do this, as the the t480 does not have tmp support, and it can be interpreted as meaning that this only needs to be done for machines with tpm support, even though required on the t480 as well.

**Comment by digmorepaka** [comment]
TPM not working is outlined in the table. Your description is a bit chaotic, not sure how you are expecting it to be worded. Create a pull request with changes that you deem necessary, it will be reviewed.
